site_name: Godot Space
site_url: https://godotc.github.io
site_author: godot42
site_description: godot42's personal site
edit_uri: edit/main/docs

## [ top-right corner ]
repo_url: https://github.com/godotc/godotc
repo_name: godotc.github.io

## [ bottom-left corner ]
copyright: Copyright &copy; 2022 godot42

#-----------------------Navigation------------------------------

# [ Navigation ]
nav:
  - Home:
      - index.md
      - 信息: HOME/detail.md
  - Blog:
      - Shell:
          - Bash 语言概览: Blog/Shell/Bash/Bash-lang.md
          - Hot Key: Blog/Shell/Bash/光标移动.md
          - 去除ls背景高光(绿色污染): Blog/Shell/Bash/去除ls背景(绿色).md
      - C/C++:
          - 函数指针: Blog/C_Cpp/函数指针.md
          - 继承: "Blog/C_Cpp/继承.md"
          - 多线程/进程: Blog/C_Cpp/MultiProcess_MultiThread.md
          - STD-IO: Blog/C_Cpp/STD_IO.md
          - 字符串处理: Blog/C_Cpp/字符串处理.md
          #- 关键字: Blog/C_CPP/关键字.md
      - Java:
          - 牛客社区项目总结: Blog/JAVA/牛客社区项目总结.md
      - Golang:
        - channel: Blog/Go/channel.md
        - RPC: Blog/Go/RPC.md
      - Linux:
          - 常忘指令: Blog/Linux/常忘指令.md
          - 换源: Blog/Linux/Linux换源.md
          - 用户与权限: Blog/Linux/用户与权限.md
          - 获取Linux版本信息: Blog/Linux/获取Linux版本信息.md
          - Pacman问题: "Blog/Linux/pacman 问题.md"
          - Select Poll Epoll: "Blog/Linux/Select Poll Epoll.md"
      - Docker:
          - Run 命令使用: Blog/Docker/Run命令.md
          - 网络管理: Blog/Docker/docker网络管理.md
      - 网络:
          - 非阻塞与异步IO: Blog/网络/阻塞与非阻塞、同步与异步、异步IO.md
          # - ip地址相关: Blog/网络/ip地址相关.md
          - Http各版本的链接: Blog/网络/Http各版本的链接.md
      - 分布式:
          - MIT 6.824:
              - Map Reduce: "Blog/分布式/MIT 6.824/Map Reduce.md"
              - 1. Distribute and GFS: "Blog/分布式/MIT 6.824/1. Distribute and GFS.md"
              - 2. Replication: "Blog/分布式/MIT 6.824/2. Replication.md"
              - 3. Go Threads and Raft: "Blog/分布式/MIT 6.824/3. Go Threads and Raft.md"
      - 数据库:
          - MYSQL:
              - 安装MYSQL: Blog/数据库/mysql/安装MYSQL.md
          - Redis 为什么这么快？: "Blog/数据库/Redis 为什么这么快.md"
      # - 服务器:
      #     - TinyWebserver中的要点: "Blog/服务器/TinyWebserver 中的要点.md"
      - 算法:
          - LeetCode: Blog/All_Go_Rhyme/LeetCode.md
          - NowCoder: Blog/All_Go_Rhyme/NowCoder.md
          #- index: "Blog/All_Go_Rhyme/Leet Code Index.md"
        

  - Tools:
      - CMake:
          - CMakeLists.txt格式: "Tools/CMake/CMkeLists_txt格式.md"
          - Modern CMake: Tools/CMake/现代CMAKE.md
          - Vcpkg的使用: "Tools/CMake/Vcpkg和CMake,Include和Link.md"
      - Vim:
          - 查找与替换: Tools/Vim/查找与替换.md
          - 多文件操作: Tools/Vim/多文件操作.md
          - 进阶操作: Tools/Vim/进阶操作.md
          - 光标操作: "Tools/Vim/光标操作 Cursor Operation.mv"
          - YCM: Tools/Vim/安装YCM.md
      - Git:
          - 分支操作: Tools/Git/分支操作.md
          - Submodule: Tools/Git/Submodule.md
          - 附加Commit: "Tools/Git/Attach to previous commit.md"

  - Frames:
      - GNU:
          - GDB操作: Frame/GNU/GDB.md
          - gcc编译器: "Frame/GNU/gcc 编译器.md"
      - LLVM:
          - Clangd: Frame/LLVM/Clangd.md

  - 面试相关:
    - TinyWebserver中的要点: 面试相关/TinyWebserver中的要点.md
    - 设计一个无锁队列: 面试相关/设计一个无锁队列.md
#---------------------------------------------------------------

# [UI]
## [top]
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default # Daylight mode
      primary: indigo # the top side
      accent: red # link etc. interaction highlight
      toggle:
        icon: material/weather-night
        name: Switch to Dark mode
    - scheme: slate # dark mode
      primary: indigo
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to Daytime mode
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    #- navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  language: en
  icon:
    repo: fontawesome/brands/github
## [ bottom-right corner ]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/12232716
      name: Bilibili | Charlestz # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/godotc
      name: GitHub | godotc

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
      # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
      separator: '[\s\u200b\-]'
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags

markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等

extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
  - mkdocs/javascripts/giscuss.js

extra_css:
  # - mkdocs/css/no-footer.css # 不使用底部的翻页
  # - mkdocs/css/unordered-list-symbols.css # multiply unordered list symbols
